import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  // Safelist critical layout/animation classes that may be dynamically applied
  safelist: [
    'animate-fade-in',
    'animate-slide-up',
    'animate-scale-in',
    'animate-float',
    'display-xl',
    'display-lg',
    'display-md',
    'display-sm',
    'text-balance',
    'text-pretty',
    'text-eyebrow',
    'container-page',
    'container-premium',
    'surface',
    'surface-subtle',
    'surface-elevated',
    'glass',
    'btn',
    'btn-primary',
    'btn-secondary',
    'btn-ghost',
    'btn-danger',
    'btn-sm',
    'btn-lg',
    'btn-xl',
    'btn-icon',
    'input-base',
    'chip',
    'chip-success',
    'chip-warning',
    'chip-danger',
    'chip-info',
    'chip-neutral',
    'atmosphere',
    'atmosphere-day',
    'atmosphere-night',
    'sun-orb',
    'moon-orb',
    'stars',
    'hills',
    'hill',
    'hill-1',
    'hill-2',
    'hill-3',
    'skeleton',
    'spinner',
    'shadow-soft',
    'shadow-lift',
    'text-gradient-brand',
    'divider',
    'no-scrollbar',
    'pb-safe',
    'pt-safe',
  ],
  darkMode: ['class', '[data-theme="night"]'],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: '1rem',
        sm: '1.5rem',
        lg: '2rem',
      },
      screens: {
        '2xl': '1280px',
      },
    },
    extend: {
      colors: {
        bg: {
          DEFAULT: 'rgb(var(--bg) / <alpha-value>)',
          elevated: 'rgb(var(--bg-elevated) / <alpha-value>)',
          subtle: 'rgb(var(--bg-subtle) / <alpha-value>)',
          overlay: 'rgb(var(--bg-overlay) / <alpha-value>)',
        },
        fg: {
          DEFAULT: 'rgb(var(--fg) / <alpha-value>)',
          muted: 'rgb(var(--fg-muted) / <alpha-value>)',
          subtle: 'rgb(var(--fg-subtle) / <alpha-value>)',
        },
        border: {
          DEFAULT: 'rgb(var(--border) / <alpha-value>)',
          strong: 'rgb(var(--border-strong) / <alpha-value>)',
        },
        ring: 'rgb(var(--ring) / <alpha-value>)',
        card: {
          DEFAULT: 'rgb(var(--card) / <alpha-value>)',
          fg: 'rgb(var(--card-fg) / <alpha-value>)',
        },
        input: {
          DEFAULT: 'rgb(var(--input) / <alpha-value>)',
          border: 'rgb(var(--input-border) / <alpha-value>)',
        },
        brand: {
          primary: 'rgb(var(--brand-primary) / <alpha-value>)',
          secondary: 'rgb(var(--brand-secondary) / <alpha-value>)',
          accent: 'rgb(var(--brand-accent) / <alpha-value>)',
        },
        success: 'rgb(var(--success) / <alpha-value>)',
        warning: 'rgb(var(--warning) / <alpha-value>)',
        danger: 'rgb(var(--danger) / <alpha-value>)',
        info: 'rgb(var(--info) / <alpha-value>)',
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'system-ui', 'sans-serif'],
        display: ['var(--font-poppins)', 'var(--font-inter)', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        'xs': '6px',
        'sm': '8px',
        'md': '12px',
        'lg': '16px',
        'xl': '20px',
        '2xl': '24px',
        '3xl': '32px',
      },
      height: {
        '13': '3.25rem',
        '15': '3.75rem',
        '18': '4.5rem',
      },
      boxShadow: {
        'soft': '0 1px 2px rgb(0 0 0 / 0.04), 0 8px 24px -12px rgb(0 0 0 / 0.08)',
        'lift': '0 1px 2px rgb(0 0 0 / 0.05), 0 16px 32px -18px rgb(0 0 0 / 0.14)',
        'inset-soft': 'inset 0 1px 0 rgb(255 255 255 / 0.08)',
        'premium': '0 18px 40px -16px rgb(0 0 0 / 0.16)',
      },
      keyframes: {
        'fade-in': {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          from: { opacity: '0', transform: 'scale(0.96)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        'slide-up': {
          from: { opacity: '0', transform: 'translateY(16px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-6px)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 480ms cubic-bezier(0.16, 1, 0.3, 1) backwards',
        'scale-in': 'scale-in 380ms cubic-bezier(0.16, 1, 0.3, 1) backwards',
        'slide-up': 'slide-up 520ms cubic-bezier(0.16, 1, 0.3, 1) backwards',
        'float': 'float 6s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};

export default config;
