export const FALLBACK_CATEGORIES = [
  {
    id: 1,
    slug: 'cattle',
    name: 'Qoramollar',
    description: '',
    icon: 'cattle',
    image: null,
    name_uz: 'Qoramollar',
    name_uz_cyrl: 'Қорамоллар',
    name_ru: 'Крупный рогатый скот',
    name_en: 'Cattle',
    breeds: [],
  },
  {
    id: 2,
    slug: 'sheep',
    name: 'Qoʻylar',
    description: '',
    icon: 'sheep',
    image: null,
    name_uz: 'Qoʻylar',
    name_uz_cyrl: 'Қўйлар',
    name_ru: 'Овцы',
    name_en: 'Sheep',
    breeds: [],
  },
  {
    id: 3,
    slug: 'goats',
    name: 'Echkilar',
    description: '',
    icon: 'goats',
    image: null,
    name_uz: 'Echkilar',
    name_uz_cyrl: 'Эчкилар',
    name_ru: 'Козы',
    name_en: 'Goats',
    breeds: [],
  },
  {
    id: 4,
    slug: 'horses',
    name: 'Otlar',
    description: '',
    icon: 'horses',
    image: null,
    name_uz: 'Otlar',
    name_uz_cyrl: 'Отлар',
    name_ru: 'Лошади',
    name_en: 'Horses',
    breeds: [],
  },
  {
    id: 5,
    slug: 'camels',
    name: 'Tuyalar',
    description: '',
    icon: 'camels',
    image: null,
    name_uz: 'Tuyalar',
    name_uz_cyrl: 'Туялар',
    name_ru: 'Верблюды',
    name_en: 'Camels',
    breeds: [],
  },
  {
    id: 6,
    slug: 'poultry',
    name: 'Parrandalar',
    description: '',
    icon: 'poultry',
    image: null,
    name_uz: 'Parrandalar',
    name_uz_cyrl: 'Паррандалар',
    name_ru: 'Птица',
    name_en: 'Poultry',
    breeds: [],
  },
];
